### ISSUE TITLE
Could not open vgg16_xml.drawio file

### ISSUE THREAD

**Issue by Acgholic** [kennethleungty/Neural-Network-Architecture-Diagrams#2]
It seems that the vgg16_xml.drawio as well as the yolo_v1_xml.drawio file could not be loaded by the https://app.diagrams.net/.  When I want to load these two files, I get this message Not a diagram file (error on line 16 at column 76: Specification mandates value for attribute crossorigin). But when I load the file I created, it works well.

**Comment by kennethleungty** [comment]
Hi @Acgholic, I just did a check and it works fine on my Chrome browser. Perhaps you can try forking and cloning this repo, and then uploading the .drawio directly from your local drive. Let me know how it goes
